plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pureplate.dev'
    compileSdk 34

    defaultConfig {
        applicationId "com.pureplate.dev"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0-dev"
    }

    buildTypes {
        debug {
            debuggable true
            applicationIdSuffix ".debug"
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'
}
